# docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: rpgdb
    ports:
      - "9996:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: