<form action="/show" method="POST">
    <fieldset>
        <legend>Create a Character</legend>
        <div>
            <label for="name"><span>Name</span>
                <input name="name" placeholder="Name" required autofocus type="text">
            </label>
        </div>
        <div>
            <label for="age"><span>Age</span>
                <input name="age" placeholder="Age" required type="number">
            </label>
        </div>
        <div>
            <label for="characterClass"><span>Class</span>
                <input name="characterClass" placeholder="Class" required type="text">
            </label>
        </div>
        <div>
            <input type="submit" value="Create">
        </div>
    </fieldset>
</form>