<?php
    use HelloWorld\Model\CharacterClass;
?>
<form action="/show" method="POST">
    <fieldset>
        <legend>Create a Character</legend>
        <div>
            <label for="name"><span>Name</span>
                <input name="name" placeholder="Name" required autofocus type="text">
            </label>
        </div>
        <div>
            <label for="age"><span>Age</span>
                <input name="age" placeholder="Age" required type="number">
            </label>
        </div>
        <div>
            <label for="characterClass"><span>Class</span>
                <?php foreach (CharacterClass::CHARACTER_CLASSES as $id => $name):?>
                    <input type="radio" id="<?= $id ?>" name="character_radio" value="<?= $id ?>">
                    <label for="<?= $id ?>"><?= $name ?></label>
                <?php endforeach ?>
            </label>
        </div>
        <div>
            <input type="submit" value="Create">
        </div>
    </fieldset>
</form>