<?php

declare(strict_types=1);

use HelloWorld\Model\Player;

/**
 * @var array<int, Player> $players
 * @var Player $player
 */
?>

<header>
    <h1>Home</h1>
    <a href="/create" class="btn">Create</a>
</header>
<ul>
    <?php foreach ($players as $player):?>
        <li class="NameBox">
            <p>Name: <?= $player->getName()?></p>
            <p>CharacterClass: <?= $player->getCharacterClass()->getValue() ?></p>
            <p>Alter: <?= $player->getAge();?></p>
            <a href="/show?playerId=<?= $player->getId() ?>" class="btn">Play</a>
            <a href="/delete?playerId=<?= $player->getId() ?>" class="btn">Delete</a>
            <a href="/update?playerId=<?= $player->getId() ?>" class="btn">Update</a>
        </li>
    <?php endforeach?>
</ul>
