<?php
    use HelloWorld\Model\CharacterClass;
?>
<form action="/update?playerId=<?= $player->getId(); ?>" method="POST" id="character">
    <fieldset>
        <legend>Update a Character</legend>
        <div class="character">
            <?php foreach (CharacterClass::CHARACTER_CLASSES as $id => $name):?>
                <input type="radio" id="<?= $id ?>" name="character_radio" class="characterClass" value="<?= $id ?>" <?php if($player->getCharacterClass()->getValue() === $id): ?>checked <?php endif ?>>
                <label for="<?= $id ?>"><span><?= $name ?></span></label>
            <?php endforeach ?>
        </div>
        <div>
            <label for="name"><span>Name</span>
                <input name="name" placeholder="Name" required autofocus type="text" class="styled" value=<?= $player->getName()?>>
            </label>
        </div>
        <div>
            <label for="age"><span>Age</span>
                <input name="age" placeholder="Age" required type="number" class="styled" value=<?= $player->getAge()?>>
            </label>
        </div>
        <div>
            <input name="submit" type="submit" value="Create" class="styledSubmit">
        </div>
    </fieldset>
</form>